# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 
TEMPLATE = subdirs

SUBDIRS += src \
           examples
#CONFIG += warn_on \
#qt \
#thread

examples.depends = src
