# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sample
# Target is a subdirs project 

TEMPLATE = subdirs

SUBDIRS += \
          #sample01 \
           sample02
#CONFIG += release \
#warn_on

