# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 
TEMPLATE = subdirs

SUBDIRS += property

#CONFIG += release \
#warn_on

